language: python
python:
- '3.5'
- '3.6'
env:
  matrix:
  - DJANGO="Django=2.1"
  - DJANGO="Django=2.2"
  - DJANGO="Django<3"

cache:
  directories:
  - "$HOME/.cache/pip"
install:
- pip install "$DJANGO"
- pip install -e .
script:
- python tests/manage.py test test_app
notifications:
  slack:
    rooms:
      secure: jxFJWa9UaphsVUCkDCWhQIt7m5hbXY1Dltk2V7c9QFyZZl7BDx9p0PrVb0IaZ19DIAbC+G1MKT+zCWvbVyAeodDVcAgSRkj2Z9+zc8Qqc/t8PEtxQR9hVIs1p9PA1yFuVcfAa1abIJiC8A19r+EWtLI29WwG9Bmq620KDxWXLoaBRMm50NoCgP+H08hWTZ9D6Z6IX1lTtg8XlycKEEok0glqmRqmEkdObnTZgEVYfc7sPbE6cIDc4v//9LQ5EEscGFlQ1Bmr3jLpAmJGvumZfMK2L9YTOvA7w/5o9aqyxI07YYtmKEQw6GEGIzIL7M6Jb9yIpzHYIx4Ib2p3OtEKrpwhEhXGS3cCCyoZve5jtID/INpB18D9qo2w8a5L42ASaCEzMxmiFSs7S4yppCvGiHCH8VLXvNMvj+Jr9Dg/BEBmygSXp9zvUPsi3UVovWX7Myeaz0PrDADNse+UyTmcuF2riRzU8lEEKB+gJIWz2a1Rc64cP+yhc4Iy1nO32YUEvpEyHDZ6/8h4yO3Y+pM0oRsDn7I9mlQZ4qAeGyEvmhJN+xdWePsyY03qzbvhVA6mwZNq8j7ga+tt3s4UM8F1M1ZzgpP56YvB1djQnb6Xg2Bo9fihzUdbKfHuEbLhgN9te3C0jF/QLUibsb4BXTJMEm4uztVW9d1W4rNzjqhBQ+4=
deploy:
  provider: pypi
  user: egregors
  password:
    secure: mrLMFx1/MUsvorsk6O1BqfL6S7vzQ7vbnO9+B+VbZ5yC+tE1tLf+Tqzc5b0K0xtlerZrF4HxXM+0IKprhItYMF2HyPvjFek/SMrfNhlOiRdMBDHQRXBlodICgAtIXkFTsK/FgVuV+GAUyl2lc1ICHu31gvJ1k2CERA3PIJxLkSbQ77Fp/5cQL8XTwAA4ABklXYnYGa0XW872Fva4GZUJB1EgK27vt8wklcY/wsL2ZqcoNsSkHv1ib6hCssTP6kzh4UKNe92RVc0FZHW50zCWEp3tXr/ulT9JC16s/z+i146xwkhjnEZNlYPDFv1VEXOkBtY7+zTbv+CBOhG1+/DaWNHNl6FZYIGpChgN7yG57C8WYxjhNR/qp3w4H8T4f+NVR2WsITf0dvkxpKHJ80gmH4JZpcmYC9LrLtPAbNwrMT99yjx6jz9javUsEo1oPQQzsplMh0DytH0EFalCacN+zOavniB2RdYR1l6hMtA/BHWTRcUJWMDWuuixFPBBu+pNULEPcZoLSh4gRwT00Qw0CjM9jc7+6Li+TPYbTEpdxV2DvJMVQ5irssI3+xgQsK/20R/rAX9YoW8ZGgYNy65uIThhacFe2vd5Alqsp8AvZRI3WtczhBf7rewY29qTinQEwYKp+0gEGPJ10HSrbyHaduC26BrCvrRQswqMeeBVpuA=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: egregors/django-cbrf
    branch: master
